Net/ThemeName "Catppuccin-Mocha-Lavender"
Net/IconThemeName "Tela-circle-dracula"
Gtk/CursorThemeName "macOS"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
